# -*- coding: utf-8 -*-
"""Practica Histograma.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sIIRpiRPj7JRkU7ZHF3HuYjknRf2V-M4
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt
from google.colab.patches import cv2_imshow

img = cv2.imread('img1.jpg', cv2.IMREAD_GRAYSCALE)
cv2_imshow(img)
print('\t')

hist = cv2.calcHist([img], [0], None, [256], [0, 256])
plt.plot(hist, color='green' )

plt.xlabel('intensidad de iluminacion')
plt.ylabel('cantidad de pixeles')
plt.show()

cv2.destroyAllWindows()